package ast.patron.compuesto;
public enum Operador{
    MAS,MENOS,POR,POTENCIA,DIV,DIVENTERA,MODULO,
    LE,GR,LEQ,GRQ,EQUALS,DIFF,EQ,
    AND,OR,NOT,
    WHILE,FOR,ELIF,ELSE,IF,
    PRINT,
    CADENA,ENTERO,REAL,BOOLEANO
}